//CATEGORY
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const CREATE_CATEGORY_RED = "CREATE_CATEGORY_RED"
export const GET_CATEGORY = "GET_CATEGORY"
export const GET_CATEGORY_RED = "GET_CATEGORY_RED"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"
export const UPDATE_CATEGORY_RED = "UPDATE_CATEGORY_RED"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const DELETE_CATEGORY_RED = "DELETE_CATEGORY_RED"


